// @ts-check
(function () {
  const vscode = acquireVsCodeApi();

  const listEl = /** @type {HTMLElement} */ (document.getElementById('plan-list'));
  const detailEl = /** @type {HTMLElement} */ (document.getElementById('detail'));
  const noticeEl = /** @type {HTMLElement} */ (document.getElementById('notice'));
  const setupEl = /** @type {HTMLElement} */ (document.getElementById('setup'));
  const searchEl = /** @type {HTMLInputElement} */ (document.getElementById('search'));
  const costEl = /** @type {HTMLElement} */ (document.getElementById('cost'));
  const activityEl = /** @type {HTMLElement} */ (document.getElementById('activity'));
  const activityListEl = /** @type {HTMLElement} */ (document.getElementById('activity-list'));
  const activityFilterEl = /** @type {HTMLSelectElement} */ (document.getElementById('activity-filter'));
  const activityToggleEl = /** @type {HTMLElement} */ (document.getElementById('activity-toggle'));
  const rootFolderEl = /** @type {HTMLSelectElement} */ (document.getElementById('root-folder'));
  const shellEl = /** @type {HTMLElement} */ (document.querySelector('.shell'));
  const librarySashEl = /** @type {HTMLElement} */ (document.getElementById('library-sash'));
  const activitySashEl = /** @type {HTMLElement} */ (document.getElementById('activity-sash'));

  const DAY_LABELS = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
  const DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

  /**
   * Approval settings, per engine. opencode has one control where Claude has
   * six, so it is offered the two that mean something — approve everything, or
   * plan only — rather than four more that would quietly map onto the same flag.
   */
  const PERMISSION_MODES = {
    claude: ['acceptEdits', 'auto', 'dontAsk', 'plan', 'bypassPermissions'],
    opencode: ['auto', 'plan']
  };

  /** Never a real model id: it starts with `_`, which the host's pattern rejects. */
  const CUSTOM_MODEL = '__custom';
  const SAVE_DEBOUNCE_MS = 2000;

  /** @type {{plans: any[], series: any[], runs: any[], activity: {upcoming: any[], recent: any[]}, costLast7Days: number, libraryPath: string, activeFolder: string, folders: {path: string, name: string}[], agents: {id: string, label: string, models: {value: string, label: string}[]}[], settings: {title: string, fields: any[]}[], settingValues: Record<string, any>, setupProblem?: string, schedulerElsewhere?: boolean}} */
  let state = {
    plans: [],
    series: [],
    runs: [],
    activity: { upcoming: [], recent: [] },
    costLast7Days: 0,
    libraryPath: '',
    // The Settings page's shape and its current readings, both generated by the
    // host from package.json's own configuration schema — so a setting cannot
    // exist without a control, and a control cannot name a setting that does not.
    settings: [],
    settingValues: {},
    // Which folder's data is on screen, and what else this workspace offers.
    // Everything here — plans, schedules, runs — belongs to `activeFolder`.
    activeFolder: '',
    folders: [],
    // Sent by the extension from `src/agents.ts`, so the sidebar's model picker
    // and these dropdowns cannot drift apart, and only engines this machine can
    // actually run are listed. Empty only before the first state message
    // arrives, which is why every read below tolerates an empty list.
    agents: []
  };

  /** Selection and editor buffer live here, never in the DOM — a re-render
   *  must never be able to lose what you typed. */
  let selected = /** @type {string|null} */ (null);
  /** Runs-panel state, held here for the same reason. */
  let activityFilter = 'all';
  let activityCollapsed = false;
  /** Pane sizes, duplicated in manager.css as the custom-property fallbacks. */
  const LIBRARY_DEFAULT = 260;
  const ACTIVITY_DEFAULT = 220;
  /** Null means "whatever the stylesheet says", so nothing is written until dragged. */
  let libraryWidth = /** @type {number|null} */ (null);
  let activityHeight = /** @type {number|null} */ (null);
  /** Whether the detail pane is showing Settings instead of a plan. */
  let showSettings = false;
  /** A plan is addressed by name alone — no path from here ever reaches the
   *  filesystem, which is what lets the host resolve every read and write
   *  through the one library guard. */
  let editor = {
    name: /** @type {string|null} */ (null),
    text: '',
    dirty: false,
    conflict: false
  };
  let saveTimer = 0;
  let noticeTimer = 0;
  let elapsedTimer = 0;
  /** Whether the Model field is showing its free-text box. Curated lists go
   *  stale, and the host validates whatever is typed by shape. */
  let customModel = false;
  /** Whether the When field's popover is showing. */
  let pickerOpen = false;
  /** Day 1 of the month the popover is looking at. Null means "wherever the
   *  scheduled time is" — browsing away from it is what sets this. */
  let pickerMonth = /** @type {Date|null} */ (null);

  /** A dragged size must never leave the other pane unusable, and the window can
   *  shrink after the drag — so every read goes back through these. */
  const clampLibrary = (px) => Math.max(180, Math.min(px, Math.max(180, Math.min(560, window.innerWidth - 360))));
  const clampActivity = (px) => Math.max(120, Math.min(px, Math.max(120, window.innerHeight - 260)));

  /** The only place the pane-size custom properties are written. Clearing one
   *  hands the size back to the stylesheet rather than pinning it at the default. */
  function applySizes() {
    const root = document.documentElement.style;
    if (libraryWidth === null) root.removeProperty('--library-width');
    else root.setProperty('--library-width', `${libraryWidth}px`);
    if (activityHeight === null) root.removeProperty('--activity-height');
    else root.setProperty('--activity-height', `${activityHeight}px`);
  }

  const previous = vscode.getState();
  if (previous && previous.selected) selected = previous.selected;
  if (previous && previous.activityFilter) activityFilter = previous.activityFilter;
  if (previous && previous.activityCollapsed) activityCollapsed = true;
  if (previous && previous.showSettings) showSettings = true;
  if (previous && previous.libraryWidth) libraryWidth = clampLibrary(previous.libraryWidth);
  if (previous && previous.activityHeight) activityHeight = clampActivity(previous.activityHeight);
  applySizes();
  activityFilterEl.value = activityFilter;
  paintActivityCollapse();

  // ---------- helpers ----------

  const pad = (n) => String(n).padStart(2, '0');
  const esc = (s) => String(s).replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);
  const samePath = (a, b) => String(a).toLowerCase() === String(b).toLowerCase();
  const send = (message) => vscode.postMessage(message);

  /** Everything that must survive a window reload, written in one place so a new
   *  key cannot be added to two of the three callers and forgotten in the third. */
  const saveViewState = () =>
    vscode.setState({ selected, activityFilter, activityCollapsed, showSettings, libraryWidth, activityHeight });

  const toUtcIso = (localValue) => new Date(localValue).toISOString();
  const localTimeOf = (iso) => {
    const d = new Date(iso);
    return `${pad(d.getHours())}:${pad(d.getMinutes())}`;
  };

  // ---------- the when picker's arithmetic ----------

  /** 24-hour clock to the 12-hour one the dropdowns show. */
  function to12(hour24) {
    return { h12: hour24 % 12 === 0 ? 12 : hour24 % 12, ampm: hour24 >= 12 ? 'PM' : 'AM' };
  }

  /** And back again. Noon and midnight are the two that do not follow the rule. */
  const from12 = (h12, ampm) =>
    ampm === 'PM' ? (h12 === 12 ? 12 : h12 + 12) : h12 === 12 ? 0 : h12;

  /** A `datetime-local`-shaped string, so it feeds straight into `toUtcIso`.
   *  `month` is 0-based, as everywhere else Date is handled here. */
  const localStr = (year, month, day, hour24, minute) =>
    `${year}-${pad(month + 1)}-${pad(day)}T${pad(hour24)}:${pad(minute)}`;

  /** Day 1 of the month an instant falls in — what the grid is drawn from. */
  function monthOf(iso) {
    const d = new Date(iso);
    return new Date(d.getFullYear(), d.getMonth(), 1);
  }

  /**
   * The month grid's cells, flat: `null` for each leading blank before the 1st
   * (Sunday-first, matching DAY_LABELS), then the days themselves. Flat rather
   * than nested weeks because a 7-column CSS grid wraps the rows for us.
   */
  function calendarWeeks(viewDate) {
    const year = viewDate.getFullYear();
    const month = viewDate.getMonth();
    const cells = new Array(new Date(year, month, 1).getDay()).fill(null);
    const last = new Date(year, month + 1, 0).getDate();
    for (let day = 1; day <= last; day++) cells.push(day);
    return cells;
  }

  function dayDiff(a, b) {
    const da = new Date(a.getFullYear(), a.getMonth(), a.getDate());
    const db = new Date(b.getFullYear(), b.getMonth(), b.getDate());
    return Math.round((da.getTime() - db.getTime()) / 86400000);
  }

  function formatWhen(iso) {
    const d = new Date(iso);
    const time = d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    const diff = dayDiff(d, new Date());
    if (diff === 0) return `Today ${time}`;
    if (diff === 1) return `Tomorrow ${time}`;
    if (diff === -1) return `Yesterday ${time}`;
    return `${d.toLocaleDateString([], { weekday: 'short', day: 'numeric', month: 'short' })} ${time}`;
  }

  function formatDuration(ms) {
    const total = Math.max(0, Math.round(ms / 1000));
    const h = Math.floor(total / 3600);
    const m = Math.floor((total % 3600) / 60);
    return h > 0 ? `${h}h ${pad(m)}m` : `${m}m ${pad(total % 60)}s`;
  }

  function formatAge(ms) {
    const minutes = Math.round((Date.now() - ms) / 60000);
    if (minutes < 1) return 'just now';
    if (minutes < 60) return `${minutes}m ago`;
    const hours = Math.round(minutes / 60);
    if (hours < 24) return `${hours}h ago`;
    return `${Math.round(hours / 24)}d ago`;
  }

  const planByName = (name) => state.plans.find((p) => p.name === name);
  const seriesForPlan = (plan) =>
    plan ? state.series.find((s) => samePath(s.filePath, plan.filePath)) : undefined;
  const seriesById = (id) => state.series.find((s) => s.id === id);

  /** The plan a panel row should select. Absent once the series is unscheduled. */
  function planForSeries(id) {
    const series = seriesById(id);
    return series ? state.plans.find((p) => samePath(p.filePath, series.filePath)) : undefined;
  }

  const repeatOf = (s) =>
    !s.recurrence
      ? 'once'
      : s.recurrence.dayOfMonth
        ? 'monthly'
        : s.recurrence.daysOfWeek.length === 7
          ? 'daily'
          : 'weekly';

  /** A series with no engine is a Claude series — the same rule the host uses. */
  const agentIdOf = (s) => (s && s.agent) || 'claude';
  const agentOf = (s) =>
    state.agents.find((a) => a.id === agentIdOf(s)) || state.agents[0];
  const modelsOf = (s) => (agentOf(s) || { models: [] }).models;

  const isRunning = (s) =>
    !!s && state.runs.some((r) => r.seriesId === s.id && r.status === 'running');

  // ---------- the time axis ----------

  /** Circumference of the ring's r=16 circle, in user units. */
  const RING_C = 100.53;

  /**
   * How long the current interval is, so the ring knows what fraction of it has
   * elapsed. A one-shot has no interval — there is nothing to be a fraction of.
   */
  function intervalMs(s) {
    if (!s || !s.recurrence) return null;

    // Monthly, before the day rules below: its `daysOfWeek` is empty. The ring
    // is cosmetic, so the real length of the preceding month is close enough.
    if (s.recurrence.dayOfMonth) {
      const next = new Date(s.nextRunAt);
      const prev = new Date(next);
      prev.setMonth(prev.getMonth() - 1);
      return next.getTime() - prev.getTime();
    }

    const days = s.recurrence.daysOfWeek;
    if (!days.length) return null;
    if (days.length === 7) return 86400000;

    // Weekly: the gap back to whichever scheduled day precedes the next run.
    const next = new Date(s.nextRunAt).getDay();
    const earlier = days.filter((d) => d !== next);
    if (!earlier.length) return 7 * 86400000;
    return Math.min(...earlier.map((d) => (next - d + 7) % 7)) * 86400000;
  }

  /** Dash offset for a full circumference dasharray: full ring at 0% elapsed. */
  function ringOffset(iso, interval) {
    const left = new Date(iso).getTime() - Date.now();
    const done = Math.min(1, Math.max(0, (interval - left) / interval));
    return (RING_C * (1 - done)).toFixed(2);
  }

  const countdownText = (iso) => {
    const left = new Date(iso).getTime() - Date.now();
    return left > 0 ? `in ${formatDuration(left)}` : 'due now';
  };

  function cadenceOf(s) {
    const time = localTimeOf(s.nextRunAt);
    const repeat = repeatOf(s);
    if (repeat === 'monthly') return `day ${s.recurrence.dayOfMonth} ${time}`;
    if (repeat === 'daily') return `daily ${time}`;
    if (repeat === 'weekly') {
      return `${s.recurrence.daysOfWeek.map((d) => DAY_NAMES[d]).join(' ')} ${time}`;
    }
    return `once · ${formatWhen(s.nextRunAt)}`;
  }

  /** The one line that answers "when does this run next?". */
  function headStatus(s) {
    if (!s) return '<p class="head-status">Not scheduled</p>';
    if (s.spent) return '<p class="head-status">Ran once</p>';
    if (!s.enabled) return '<p class="head-status">Paused</p>';
    if (isRunning(s)) return '<p class="head-status"><span class="head-count">running now</span></p>';
    return `<p class="head-status">
      <span class="head-count" data-countdown="${esc(s.nextRunAt)}">${esc(countdownText(s.nextRunAt))}</span>
      &middot; ${esc(cadenceOf(s))}
    </p>`;
  }

  /**
   * Future time, cyclical. The arc fills as the current interval elapses. A live
   * run replaces it with a sweep; a one-shot gets an outline and no arc, which is
   * honest rather than inventing a progress figure.
   */
  function ringMarkup(s) {
    const track = '<circle class="ring-track" cx="20" cy="20" r="16" />';
    const interval = intervalMs(s);
    const live = s && s.enabled && !s.spent;

    let inner = '';
    if (isRunning(s)) {
      inner = '<circle class="ring-sweep" cx="20" cy="20" r="16" />';
    } else if (live && interval) {
      inner = `<circle class="ring-arc" cx="20" cy="20" r="16"
        data-ring-next="${esc(s.nextRunAt)}" data-ring-interval="${interval}"
        stroke-dasharray="${RING_C}" stroke-dashoffset="${ringOffset(s.nextRunAt, interval)}" />`;
    }

    return `<svg class="ring" viewBox="0 0 40 40" aria-hidden="true">${track}${inner}</svg>`;
  }

  // ---------- render ----------

  /**
   * Rebuilding innerHTML destroys focus and cursor position. Rather than reach
   * for a framework, the two places it matters are handled explicitly: focus is
   * restored around a render, and the editor is written from our own buffer.
   */
  function withFocusPreserved(render) {
    const active = /** @type {HTMLElement|null} */ (document.activeElement);
    const key = active && active.dataset ? active.dataset.focusKey : undefined;
    const start = active && 'selectionStart' in active ? active.selectionStart : null;
    const end = active && 'selectionEnd' in active ? active.selectionEnd : null;

    render();

    if (!key) return;
    const restored = /** @type {any} */ (document.querySelector(`[data-focus-key="${key}"]`));
    if (!restored) return;
    restored.focus();
    if (start !== null && 'setSelectionRange' in restored) {
      try {
        restored.setSelectionRange(start, end);
      } catch {
        // Not all input types support selection ranges.
      }
    }
  }

  /**
   * The folder switcher. Hidden entirely for a single-folder workspace, where
   * there is nothing to choose and the control would only be one more thing to
   * read past.
   */
  function renderFolders() {
    if (state.folders.length < 2) {
      rootFolderEl.hidden = true;
      return;
    }

    rootFolderEl.hidden = false;
    rootFolderEl.textContent = '';
    for (const folder of state.folders) {
      const option = document.createElement('option');
      option.value = folder.path;
      option.textContent = folder.name;
      option.selected = folder.path === state.activeFolder;
      rootFolderEl.append(option);
    }
  }

  /** Last segment of the active folder's path, for messages that name it. */
  function folderName() {
    return state.activeFolder.split(/[\\/]/).filter(Boolean).pop() || state.activeFolder;
  }

  function render() {
    withFocusPreserved(() => {
      renderFolders();
      renderList();
      renderDetail();
      renderActivity();
    });

    costEl.textContent =
      state.costLast7Days > 0 ? `$${state.costLast7Days.toFixed(2)} over the last 7 days` : '';

    // A broken CLI outranks a dormant scheduler: it breaks every window, not
    // just this one.
    if (state.setupProblem) {
      setupEl.textContent = `Chronos cannot reach the Claude CLI. ${state.setupProblem}`;
      setupEl.hidden = false;
    } else if (state.schedulerElsewhere) {
      // The folder is named because, now that Chronos data is per folder, this
      // can only mean a second window on *this* folder. Seeing it in a window on
      // a different project would be a bug, and you should be able to tell.
      setupEl.textContent =
        `Another window is open on this same folder (${folderName()}) and is running its ` +
        'schedule. Nothing will run from this window.';
      setupEl.hidden = false;
    } else {
      setupEl.hidden = true;
    }

    startTicker();
    saveViewState();
  }

  /** Mirrors `recency` in src/history.ts, which orders runs by the same rule. */
  const recencyOf = (run) => run.finishedAt ?? run.missedAt ?? run.startedAt ?? run.scheduledAt;

  /** The newest run of a series, whatever became of it. */
  function lastRun(series) {
    return state.runs
      .filter((r) => r.seriesId === series.id)
      .sort((a, b) => recencyOf(b).localeCompare(recencyOf(a)))[0];
  }

  function renderList() {
    const term = searchEl.value.trim().toLowerCase();
    const match = (p) => !term || p.title.toLowerCase().includes(term);

    // Nothing to hide here any more. A one-shot that completed has had its file
    // moved to `.chronos/archive/plans`, so it is not in `state.plans` at all —
    // a failed one is, and stays visible, because it is still there to be fixed
    // and run again. Its runs stay under Runs either way.
    const plans = state.plans.filter(match);

    if (!plans.length) {
      listEl.innerHTML = `<p class="empty">${
        term ? 'No plans match.' : 'No plans yet.<br />Create one to get started.'
      }</p>`;
      return;
    }

    // No group heading: there is one kind of plan, so a heading over the only
    // group names nothing.
    listEl.innerHTML = plans.map(planItem).join('');
  }

  /** The line under a plan's name: where that plan is in its life. */
  function planMeta(plan, series) {
    if (!series) {
      return plan.modifiedMs ? `Edited ${formatAge(plan.modifiedMs)}` : 'Not scheduled';
    }
    if (!series.spent) {
      return series.enabled ? formatWhen(series.nextRunAt) : 'Paused';
    }

    // Spent, so there is no next occurrence to name — say how it ended instead.
    const run = lastRun(series);
    if (!run) return 'Ran once';
    if (run.status === 'pending') return 'Queued';
    if (run.status === 'running') return 'Running now';
    if (run.status === 'missed') return 'Missed';
    return 'Ran once';
  }

  /**
   * The colour that line carries. A missed occurrence outranks everything else —
   * it is the one thing in this list still waiting on a decision, and a recurring
   * series has already advanced to a future time that would otherwise read as
   * healthy. Neutral is deliberate for a finished plan or a run in flight: the row
   * already says both another way.
   */
  function metaState(series) {
    if (series && state.runs.some((r) => r.seriesId === series.id && r.status === 'missed')) {
      return 'is-missed';
    }
    if (!series || !series.enabled) return 'is-idle';
    return series.spent ? '' : 'is-live';
  }

  function planItem(plan) {
    const series = seriesForPlan(plan);
    const meta = planMeta(plan, series);
    const metaClass = metaState(series);
    // The one case where the text does not already say it: a recurring plan
    // shows its next time, in red, because an earlier occurrence was missed.
    const missedTitle =
      metaClass === 'is-missed'
        ? ' title="Missed an occurrence — run it now, or skip it, under Runs"'
        : '';

    const classes = [
      'plan-item',
      plan.name === selected ? 'is-selected' : '',
      isRunning(series) ? 'is-running' : ''
    ].join(' ');

    const actions = `<span class="plan-actions">
        <button class="plan-action" type="button" data-action="rename"
          data-name="${esc(plan.name)}" data-focus-key="rename-${esc(plan.name)}"
          title="Rename plan" aria-label="Rename ${esc(plan.title)}">&#9998;</button>
        <button class="plan-action is-danger" type="button" data-action="archive"
          data-name="${esc(plan.name)}" data-focus-key="archive-${esc(plan.name)}"
          title="Archive plan" aria-label="Archive ${esc(plan.title)}"><i class="codicon codicon-archive"></i></button>
      </span>`;

    // A row is a wrapper holding several buttons rather than one button, because
    // a button cannot be nested inside a button.
    return `<div class="plan-row">
      <button class="${classes}" type="button"
        data-action="select" data-name="${esc(plan.name)}" data-focus-key="plan-${esc(plan.name)}">
        <span class="plan-name">${esc(plan.title)}</span>
        <span class="plan-meta ${metaClass}"${missedTitle}>${esc(meta)}</span>
      </button>
      ${actions}
    </div>`;
  }

  function renderDetail() {
    // Before the plan lookup: the settings page has no plan and no series behind
    // it, and every helper below assumes one.
    if (showSettings) {
      detailEl.innerHTML = settingsPage();
      return;
    }

    const plan = planByName(selected);
    if (!plan) {
      detailEl.innerHTML = state.plans.length
        ? '<p class="empty">Select a plan, or create one.</p>'
        : firstRunEmptyState();
      return;
    }

    // Write the plan, decide when it runs, read what happened — then the rare
    // and destructive management actions, last.
    const series = seriesForPlan(plan);
    detailEl.innerHTML = `
      <div class="detail-head">
        ${ringMarkup(series)}
        <div class="head-text">
          <div class="head-title-row">
            <h2 class="detail-title">${esc(plan.title)}</h2>
          </div>
          ${headStatus(series)}
          <p class="detail-path">${esc(plan.filePath)}</p>
        </div>
      </div>
      ${editorSection()}
      ${series ? scheduleSection(series) : unscheduledSection(plan)}
      ${series ? runsSection(series) : ''}
    `;

    mountEditor(plan);
  }

  // ---------- settings ----------

  /**
   * Every `chronos.*` setting, on the page rather than behind VS Code's own
   * Settings editor. The shape comes from the host, which builds it from
   * package.json's configuration schema — nothing about which setting exists,
   * what type it is or what it may hold is decided here.
   */
  function settingsPage() {
    return `
      <div class="detail-head">
        <div class="head-text">
          <div class="head-title-row">
            <h2 class="detail-title">Settings</h2>
          </div>
          <p class="detail-path">These are your user settings, and apply to every folder.</p>
        </div>
      </div>
      ${(state.settings || []).map(settingGroup).join('')}
      <div class="actions">
        <button class="link-button" type="button" data-action="native-settings">Edit in VS Code Settings ↗</button>
      </div>`;
  }

  function settingGroup(group) {
    // Not `.grid`: help text under each control makes a multi-column layout ragged.
    return `<div class="section">
      <h3 class="section-title">${esc(group.title)}</h3>
      <div class="settings">${group.fields.map(settingField).join('')}</div>
    </div>`;
  }

  function settingField(field) {
    const value = (state.settingValues || {})[field.key];
    const help = field.help ? `<p class="field-help">${esc(field.help)}</p>` : '';
    // The focus key is what carries the cursor across the re-render the host's
    // configuration listener triggers the moment a write lands.
    const attrs = `data-setting="${esc(field.key)}" data-focus-key="setting-${esc(field.key)}"`;

    if (field.options) {
      return `<label class="field">
        <span class="field-label">${esc(field.label)}</span>
        <select class="field-input" ${attrs}>
          ${field.options
            .map(
              (o) =>
                `<option value="${esc(o.value)}" ${o.value === value ? 'selected' : ''}>${esc(o.label)}</option>`
            )
            .join('')}
        </select>
        ${help}
      </label>`;
    }

    if (field.type === 'boolean') {
      return `<div class="field">
        <label class="field-check">
          <input type="checkbox" ${attrs} ${value ? 'checked' : ''} />
          <span class="field-label">${esc(field.label)}</span>
        </label>
        ${help}
      </div>`;
    }

    if (field.type === 'number') {
      const min = field.minimum === undefined ? '' : ` min="${esc(field.minimum)}"`;
      const max = field.maximum === undefined ? '' : ` max="${esc(field.maximum)}"`;
      return `<label class="field">
        <span class="field-label">${esc(field.label)}</span>
        <input class="field-input" type="number" ${attrs}${min}${max} value="${esc(value)}" />
        ${help}
      </label>`;
    }

    return `<label class="field">
      <span class="field-label">${esc(field.label)}</span>
      <input class="field-input" type="text" ${attrs} value="${esc(value)}" spellcheck="false" />
      ${help}
    </label>`;
  }

  function firstRunEmptyState() {
    return `<div class="empty-first-run">
      <h2 class="empty-title">Schedule Claude Code tasks from Markdown plans</h2>
      <p>Chronos runs a plan file with the Claude CLI on a schedule you choose —
        once, daily, or on set weekdays — and saves a transcript of every run.</p>
      <p>Two ways to add a plan:</p>
      <ul class="empty-ways">
        <li><strong>New plan</strong> — create one in your library and edit it here.</li>
        <li><strong>Drop a <code>.md</code> file</strong> anywhere on this window, or use
          <strong>Import</strong>, to schedule a plan you already have.</li>
      </ul>
    </div>`;
  }

  /** The one control that schedules an unscheduled plan and, once scheduled,
   *  toggles it between live and paused. Amber only while it is actually live. */
  function scheduleToggle(plan, series) {
    const live = !!series && series.enabled && !series.spent;
    const label = !series ? 'Schedule' : series.enabled ? 'Scheduled' : 'Paused';
    // Keyed off `enabled`, not `live`: a spent one-shot is still enabled, so a
    // click pauses it — the tooltip has to name the click's actual effect.
    const title = !series
      ? 'Schedule this plan'
      : series.enabled ? 'Scheduled — click to pause' : 'Paused — click to resume';
    return `<button class="button is-quiet schedule-toggle${live ? ' is-scheduled' : ''}"
      type="button" data-action="schedule-toggle" title="${esc(title)}">${label}</button>`;
  }

  function unscheduledSection(plan) {
    return `<div class="section">
      <h3 class="section-title">Schedule</h3>
      <p class="plan-meta">This plan is not scheduled.</p>
      <div class="actions">
        ${scheduleToggle(plan, null)}
      </div>
    </div>`;
  }

  function scheduleSection(s) {
    const repeat = repeatOf(s);
    const dayToggles =
      repeat === 'weekly'
        ? `<div class="days">${DAY_LABELS.map(
            (label, i) =>
              `<button class="day ${s.recurrence.daysOfWeek.includes(i) ? 'is-on' : ''}" type="button"
                data-action="day" data-day="${i}" title="${DAY_NAMES[i]}">${label}</button>`
          ).join('')}</div>`
        : '';

    // The status used to live in this heading; it is the head's job now.
    return `<div class="section">
      <h3 class="section-title">Schedule</h3>
      <div class="grid">
        ${whenField(s)}

        <label class="field">
          <span class="field-label">Repeat</span>
          <select class="field-input" data-field="repeat" data-focus-key="repeat">
            ${['once', 'daily', 'weekly', 'monthly']
              .map((v) => `<option value="${v}" ${v === repeat ? 'selected' : ''}>${v[0].toUpperCase() + v.slice(1)}</option>`)
              .join('')}
          </select>
        </label>

        ${permissionField(s)}
        ${engineField(s)}
        ${modelField(s)}
      </div>
      ${dayToggles}

      <div class="field is-spaced">
        <span class="field-label">Working directory</span>
        <div class="field-row">
          <span class="path-value" title="${esc(s.cwd)}">${esc(s.cwd)}</span>
          <button class="button is-quiet" type="button" data-action="browse-cwd">Change</button>
        </div>
      </div>

      <div class="actions">
        <button class="button" type="button" data-action="run-now">Run now</button>
        ${scheduleToggle(planByName(selected), s)}
        <button class="button is-quiet is-danger" type="button" data-action="unschedule">Unschedule</button>
      </div>
    </div>`;
  }

  /**
   * When this runs. A native `datetime-local` asked you to type into six
   * segments, and opened a calendar drawn by the browser that no selector here
   * could reach. This one is a button and, once open, plain DOM: click a day,
   * pick an hour. `pickerOpen` lives outside the DOM because every patch rebuilds
   * the pane — the same reason the Model field's custom box does.
   */
  function whenField(s) {
    return `<div class="field">
      <span class="field-label">When</span>
      <div class="when-picker">
        <button class="when-trigger" type="button" data-action="picker-toggle"
          data-focus-key="when" aria-expanded="${pickerOpen}">
          <span>${esc(formatWhen(s.nextRunAt))}</span>
          <i class="codicon codicon-calendar" aria-hidden="true"></i>
        </button>
        ${pickerOpen ? pickerPopover(s) : ''}
      </div>
    </div>`;
  }

  function pickerPopover(s) {
    const at = new Date(s.nextRunAt);
    const view = pickerMonth || monthOf(s.nextRunAt);
    const today = new Date();

    // A blank leading cell is a bare span: the grid gives it its column, and it
    // is not a day you can click.
    const days = calendarWeeks(view)
      .map((day) => {
        if (!day) return '<span></span>';
        const cell = new Date(view.getFullYear(), view.getMonth(), day);
        // Past days stay clickable — the native input allowed them, and the host
        // is the one that decides what a past time means.
        const classes = [
          'picker-day',
          dayDiff(cell, today) < 0 ? 'is-muted' : '',
          dayDiff(cell, today) === 0 ? 'is-today' : '',
          dayDiff(cell, at) === 0 ? 'is-selected' : ''
        ].join(' ');
        return `<button class="${classes}" type="button" data-action="picker-day"
          data-date="${view.getFullYear()}-${pad(view.getMonth() + 1)}-${pad(day)}">${day}</button>`;
      })
      .join('');

    return `<div class="picker-popover">
      <div class="picker-head">
        <button class="picker-nav" type="button" data-action="picker-prev"
          data-focus-key="picker-prev" title="Previous month" aria-label="Previous month">
          <i class="codicon codicon-chevron-left"></i>
        </button>
        <span>${esc(view.toLocaleDateString([], { month: 'long', year: 'numeric' }))}</span>
        <button class="picker-nav" type="button" data-action="picker-next"
          data-focus-key="picker-next" title="Next month" aria-label="Next month">
          <i class="codicon codicon-chevron-right"></i>
        </button>
      </div>
      <div class="picker-grid">
        ${DAY_LABELS.map((label, i) => `<span class="picker-weekday" title="${DAY_NAMES[i]}">${label}</span>`).join('')}
        ${days}
      </div>
      ${timeRow(at)}
    </div>`;
  }

  /** Hour, minute and meridiem as three dropdowns — nothing to type. */
  function timeRow(at) {
    const { h12, ampm } = to12(at.getHours());
    const minute = at.getMinutes();

    // Five-minute steps, plus whatever minute is already set. A series scheduled
    // for :07 must not be silently rounded to :05 by opening its own picker.
    const minutes = [];
    for (let m = 0; m < 60; m += 5) minutes.push(m);
    if (!minutes.includes(minute)) minutes.push(minute);
    minutes.sort((a, b) => a - b);

    const option = (value, label, on) =>
      `<option value="${value}" ${on ? 'selected' : ''}>${label}</option>`;

    return `<div class="picker-time">
      <select class="field-input" data-field="pickerHour" data-focus-key="picker-hour" aria-label="Hour">
        ${Array.from({ length: 12 }, (_, i) => option(i + 1, i + 1, i + 1 === h12)).join('')}
      </select>
      <select class="field-input" data-field="pickerMinute" data-focus-key="picker-minute" aria-label="Minute">
        ${minutes.map((m) => option(m, pad(m), m === minute)).join('')}
      </select>
      <select class="field-input" data-field="pickerAmpm" data-focus-key="picker-ampm" aria-label="AM or PM">
        ${['AM', 'PM'].map((v) => option(v, v, v === ampm)).join('')}
      </select>
    </div>`;
  }

  /**
   * Only the modes the chosen engine actually has. When a series carries a mode
   * the engine does not offer — a Claude task switched to opencode still stores
   * `bypassPermissions` — the nearest equivalent is shown rather than written,
   * so switching back does not lose the original choice. What is shown is what
   * the run will do: `buildArgs` maps all four permissive modes onto `--auto`.
   */
  function permissionField(s) {
    const modes = PERMISSION_MODES[agentIdOf(s)] || PERMISSION_MODES.claude;
    const current = modes.includes(s.permissionMode) ? s.permissionMode : 'auto';

    return `<label class="field">
      <span class="field-label">Permissions</span>
      <select class="field-input" data-field="permissionMode" data-focus-key="perm">
        ${modes
          .map(
            (m) =>
              `<option value="${m}" ${m === current ? 'selected' : ''}>${m}${m === 'bypassPermissions' ? ' ⚠' : ''}</option>`
          )
          .join('')}
      </select>
    </label>`;
  }

  /**
   * Hidden when there is nothing to choose between — a machine with only the
   * Claude CLI installed gets the field it had before engines existed. It
   * reappears if a task is already pinned to an engine that has since gone
   * missing, so that is visible rather than silent.
   */
  function engineField(s) {
    if (state.agents.length < 2 && agentIdOf(s) === 'claude') return '';

    const options = state.agents.some((a) => a.id === agentIdOf(s))
      ? state.agents
      : [...state.agents, { id: agentIdOf(s), label: `${agentIdOf(s)} (not installed)` }];

    return `<label class="field">
      <span class="field-label">Engine</span>
      <select class="field-input" data-field="agent" data-focus-key="agent">
        ${options
          .map(
            (a) =>
              `<option value="${esc(a.id)}" ${a.id === agentIdOf(s) ? 'selected' : ''}>${esc(a.label)}</option>`
          )
          .join('')}
      </select>
    </label>`;
  }

  /**
   * The engine's curated list, plus a free-text box. The lists are hand-kept —
   * neither CLI can enumerate what your account reaches — so anything newer than
   * this build is typed in, and the host validates it by shape.
   */
  function modelField(s) {
    const models = modelsOf(s);
    const current = s.model || '';
    const listed = models.some((m) => m.value === current);
    const custom = customModel || (!!current && !listed);

    const box = custom
      ? `<label class="field">
          <span class="field-label">Model id</span>
          <input class="field-input" type="text" data-field="customModel" data-focus-key="custom-model"
            value="${esc(current)}" placeholder="provider/model" spellcheck="false" />
        </label>`
      : '';

    return `<label class="field">
      <span class="field-label">Model</span>
      <select class="field-input" data-field="model" data-focus-key="model">
        ${models
          .map(
            (m) =>
              `<option value="${esc(m.value)}" ${!custom && m.value === current ? 'selected' : ''}>${esc(m.label)}</option>`
          )
          .join('')}
        <option value="${CUSTOM_MODEL}" ${custom ? 'selected' : ''}>Custom…</option>
      </select>
    </label>
    ${box}`;
  }

  function editorSection() {
    return `<div class="section">
      <div class="section-head">
        <h3 class="section-title">Plan text</h3>
        <button class="link-button" type="button" data-action="open-editor">Open in editor ↗</button>
      </div>
      <textarea class="editor" data-field="editor" data-focus-key="editor"
        spellcheck="false" aria-label="Plan text"></textarea>
      <p class="editor-status" data-role="editor-status"></p>
    </div>`;
  }

  function runsSection(s) {
    const runs = state.runs
      .filter((r) => r.seriesId === s.id)
      .sort((a, b) => (b.finishedAt ?? b.scheduledAt).localeCompare(a.finishedAt ?? a.scheduledAt))
      .slice(0, 20);

    if (!runs.length) {
      return `<div class="section"><h3 class="section-title">Runs</h3>
        <p class="plan-meta">No runs yet.</p></div>`;
    }

    return `<div class="section">
      <h3 class="section-title">Runs</h3>
      <div class="runs">${runs.map((r) => runRow(r, s)).join('')}</div>
    </div>`;
  }

  /**
   * A run you would want to be told about. Cancelling is not on the list: you
   * did that yourself, so it is history rather than something to chase.
   */
  const needsAttention = (run) =>
    run.status === 'failed' || run.status === 'missed' || !!run.authFailure || !!run.denials;

  /** The spine dot carries the same verdict as the badges, so the rail scans. */
  function dotClass(run) {
    if (run.status === 'running') return 'is-running';
    if (run.status === 'pending') return 'is-queued';
    if (needsAttention(run)) return 'is-bad';
    return run.status === 'completed' ? 'is-ok' : '';
  }

  /** Shared by the per-plan section and the Runs panel, so the two cannot drift. */
  function runBadges(run) {
    const badges = [];
    if (run.status === 'completed') badges.push('<span class="badge is-ok">completed</span>');
    if (run.status === 'failed') badges.push('<span class="badge is-bad">failed</span>');
    if (run.status === 'missed') badges.push('<span class="badge is-bad">missed</span>');
    if (run.status === 'cancelled') badges.push('<span class="badge">cancelled</span>');
    if (run.status === 'pending') badges.push('<span class="badge is-queued">queued</span>');
    if (run.authFailure) badges.push('<span class="badge is-bad">auth required</span>');
    if (run.attempt > 1) badges.push(`<span class="badge">retry ${run.attempt - 1}</span>`);
    if (run.denials) badges.push(`<span class="badge is-bad">⚠ ${run.denials} denied</span>`);
    if (run.costUsd) badges.push(`<span class="badge">$${run.costUsd.toFixed(2)}</span>`);
    return badges;
  }

  function runActions(run, series) {
    const actions = [];
    if (run.status === 'running') {
      actions.push(`<button class="link-button" type="button" data-action="cancel-run" data-run="${run.id}">cancel</button>`);
    } else if (run.status === 'missed') {
      // A recurring series has already advanced to its next occurrence, so the
      // only question is catch-up; a one-shot can be put back on the schedule.
      actions.push(`<button class="link-button" type="button" data-action="run-now" data-run="${run.id}">run now</button>`);
      actions.push(
        series && series.recurrence
          ? `<button class="link-button" type="button" data-action="dismiss-run" data-run="${run.id}">skip</button>`
          : `<button class="link-button" type="button" data-action="reschedule" data-run="${run.id}">reschedule</button>`
      );
    } else if (run.status === 'pending') {
      actions.push(`<button class="link-button" type="button" data-action="dismiss-run" data-run="${run.id}">skip</button>`);
    }
    if (run.resultPath) {
      actions.push(`<button class="link-button" type="button" data-action="open-result" data-run="${run.id}">result</button>`);
    }
    if (run.logPath) {
      actions.push(`<button class="link-button" type="button" data-action="open-log" data-run="${run.id}">raw log</button>`);
    }
    return actions;
  }

  /** A missed run has no result to show. This is what it says instead. */
  function missedNote(run) {
    if (run.status !== 'missed') return '';
    return `Missed${run.missedCount > 1 ? ` ${run.missedCount} occurrences` : ''}${
      run.missedReason === 'sleep' ? ' — machine asleep' : ' — VS Code closed'
    }`;
  }

  const whenText = (run) =>
    run.status === 'running' && run.startedAt
      ? `running <span data-started="${run.startedAt}">0m 00s</span>`
      : esc(formatWhen(run.scheduledAt));

  function runRow(run, series) {
    const note = missedNote(run);

    // The manager is where you sit down and read, so the summary is shown in
    // full rather than clamped the way the panel clamps it.
    const result = run.result ? `<p class="run-result">${esc(run.result)}</p>` : '';

    return `<div class="run">
      <span class="run-dot ${dotClass(run)}"></span>
      <div class="run-line">
        <span class="run-when">${whenText(run)}</span>
        ${runBadges(run).join('')}
        ${runActions(run, series).join('')}
      </div>
      ${note ? `<p class="run-result">${esc(note)}</p>` : ''}
      ${result}
    </div>`;
  }

  // ---------- the Runs panel: every plan, upcoming and recent ----------

  /**
   * The overview the per-plan Runs section cannot give: what is coming up and
   * what has already happened, across the whole library. Entries carry ids only
   * — the run itself is looked up in the `runs` array already on hand.
   */
  function renderActivity() {
    const activity = state.activity || { upcoming: [], recent: [] };
    const runById = new Map(state.runs.map((r) => [r.id, r]));

    const upcoming = activityFilter === 'all' || activityFilter === 'upcoming' ? activity.upcoming : [];
    const recent = (activityFilter === 'all' || activityFilter === 'completed' || activityFilter === 'attention'
      ? activity.recent
      : []
    ).filter((entry) => {
      const run = runById.get(entry.runId);
      if (!run) return false;
      if (activityFilter === 'completed') return run.status === 'completed';
      if (activityFilter === 'attention') return needsAttention(run);
      return true;
    });

    if (!upcoming.length && !recent.length) {
      activityListEl.innerHTML = `<p class="activity-empty">${
        activityFilter === 'all' ? 'Nothing scheduled or run yet.' : 'Nothing matches this filter.'
      }</p>`;
      return;
    }

    let html = '';
    if (upcoming.length) {
      html += `<p class="activity-group">Upcoming</p>${upcoming
        .map((entry) => activityRow(entry, runById.get(entry.runId)))
        .join('')}`;
    }
    if (recent.length) {
      html += `<p class="activity-group">Recent</p>${recent
        .map((entry) => activityRow(entry, runById.get(entry.runId)))
        .join('')}`;
    }
    activityListEl.innerHTML = html;
  }

  function activityRow(entry, run) {
    const plan = planForSeries(entry.seriesId);
    const title = plan
      ? `<button class="activity-plan" type="button" data-action="select" data-name="${esc(plan.name)}">${esc(entry.planTitle)}</button>`
      : `<span class="activity-plan is-gone">${esc(entry.planTitle)}</span>`;

    // No run record yet — a series' next occurrence. Nothing to cancel or skip,
    // so the row is a hollow dot and a countdown, and offers no actions.
    if (!run) {
      return `<div class="activity-row" data-series="${esc(entry.seriesId)}">
        <span class="run-dot"></span>
        ${title}
        <span class="activity-when">${esc(formatWhen(entry.at))}</span>
        <span class="activity-when is-count" data-countdown="${esc(entry.at)}">${esc(countdownText(entry.at))}</span>
      </div>`;
    }

    const series = seriesById(entry.seriesId);
    const note = run.result || missedNote(run);
    const countdown =
      run.status === 'pending' && Date.parse(run.scheduledAt) > Date.now()
        ? `<span class="activity-when is-count" data-countdown="${esc(run.scheduledAt)}">${esc(countdownText(run.scheduledAt))}</span>`
        : '';

    return `<div class="activity-row" data-series="${esc(entry.seriesId)}">
      <span class="run-dot ${dotClass(run)}"></span>
      ${title}
      <span class="activity-when">${whenText(run)}</span>
      ${countdown}
      ${runBadges(run).join('')}
      ${note ? `<span class="activity-note">${esc(note)}</span>` : ''}
      <span class="activity-actions">${runActions(run, series).join('')}</span>
    </div>`;
  }

  function paintActivityCollapse() {
    activityEl.classList.toggle('is-collapsed', activityCollapsed);
    activityToggleEl.setAttribute('aria-expanded', String(!activityCollapsed));
    activityToggleEl.textContent = activityCollapsed ? 'Show' : 'Hide';
  }

  // ---------- editor ----------

  /** Written from our buffer, never from state, so a re-render cannot lose typing. */
  function mountEditor(plan) {
    const area = /** @type {HTMLTextAreaElement|null} */ (detailEl.querySelector('[data-field="editor"]'));
    if (!area) return;

    if (editor.name !== plan.name) {
      editor = { name: plan.name, text: '', dirty: false, conflict: false };
      send({ type: 'loadPlan', name: plan.name });
    }
    area.value = editor.text;
    paintEditorStatus();
  }

  function paintEditorStatus() {
    const el = detailEl.querySelector('[data-role="editor-status"]');
    if (!el) return;

    el.classList.toggle('is-dirty', editor.dirty && !editor.conflict);
    el.classList.toggle('is-conflict', editor.conflict);
    el.textContent = editor.conflict
      ? 'Changed on disk while you were editing. Save to keep your version, or reopen the plan to discard it.'
      : editor.dirty
        ? 'Unsaved changes…'
        : 'Saved';
  }

  function queueSave() {
    clearTimeout(saveTimer);
    saveTimer = setTimeout(saveNow, SAVE_DEBOUNCE_MS);
  }

  function saveNow() {
    clearTimeout(saveTimer);
    if (!editor.name || !editor.dirty) return;
    send({ type: 'savePlan', name: editor.name, text: editor.text });
    editor.dirty = false;
    editor.conflict = false;
    paintEditorStatus();
  }

  /** Drives everything on screen that moves with the clock: the elapsed timer of
   *  a live run, the head countdown, the ring's arc, and the Runs panel. Scoped
   *  to the document rather than the detail pane, because the panel is outside
   *  it and its countdowns must tick too. */
  function startTicker() {
    clearInterval(elapsedTimer);
    if (!document.querySelector('[data-started], [data-countdown], [data-ring-next]')) return;

    const tick = () => {
      document.querySelectorAll('[data-started]').forEach((el) => {
        el.textContent = formatDuration(Date.now() - new Date(el.dataset.started).getTime());
      });
      document.querySelectorAll('[data-countdown]').forEach((el) => {
        el.textContent = countdownText(el.dataset.countdown);
      });
      // CSP forbids inline styles, so the ring moves via its SVG presentation
      // attribute rather than el.style.
      document.querySelectorAll('[data-ring-next]').forEach((el) => {
        el.setAttribute(
          'stroke-dashoffset',
          ringOffset(el.dataset.ringNext, Number(el.dataset.ringInterval))
        );
      });
    };

    tick();
    elapsedTimer = setInterval(tick, 1000);
  }

  // ---------- events ----------

  /** Select, rename or delete, from whichever plan row was clicked. */
  function planClick(e) {
    const el = /** @type {HTMLElement} */ (e.target).closest('[data-action]');
    if (!el) return;
    const action = /** @type {HTMLElement} */ (el).dataset.action;
    const name = /** @type {HTMLElement} */ (el).dataset.name ?? null;

    // A queued save would write the file back moments after the delete removed
    // it, so a pending edit to this plan is dropped rather than resurrected.
    if (action === 'archive') {
      if (editor.name === name) {
        clearTimeout(saveTimer);
        editor.dirty = false;
      }
      return send({ type: 'archivePlan', name });
    }

    // The opposite of delete: a rename moves the file, so anything typed has to
    // reach the old path first or it lands in a file that no longer exists.
    if (action === 'rename') {
      saveNow();
      return send({ type: 'renamePlan', name });
    }

    if (action !== 'select') return;
    saveNow();
    selectPlan(name);
  }

  listEl.addEventListener('click', planClick);

  searchEl.addEventListener('input', renderList);

  /**
   * Everything a run row offers, keyed by run id and the series that owns it —
   * never by the current selection. That is what lets the Runs panel act on a
   * run belonging to a plan you are not looking at. Returns whether it handled
   * the action, so each caller can go on to its own.
   */
  function runAction(action, runId, series) {
    if (action === 'open-log') {
      send({ type: 'openLog', id: runId });
      return true;
    }
    if (action === 'open-result') {
      send({ type: 'openResult', id: runId });
      return true;
    }
    if (action === 'cancel-run') {
      send({ type: 'cancelRun', id: runId });
      return true;
    }
    if (action === 'dismiss-run') {
      send({ type: 'dismissRun', id: runId });
      return true;
    }

    if (!series) return false;

    // Passing dismissRunId is harmless when absent — the Run now in the schedule
    // section carries no run, a missed run's Run now clears itself as it fires.
    if (action === 'run-now') {
      send({ type: 'runNow', seriesId: series.id, dismissRunId: runId });
      return true;
    }

    if (action === 'reschedule') {
      const run = state.runs.find((r) => r.id === runId);
      send({ type: 'dismissRun', id: runId });
      // Prefill the missed run's own time of day on its next occurrence, and
      // clear `spent` so the one-shot is genuinely back on the schedule.
      patch(series.id, {
        nextRunAt: nextAtTimeOf(run ? run.scheduledAt : series.nextRunAt),
        enabled: true,
        spent: false
      });
      return true;
    }

    return false;
  }

  activityListEl.addEventListener('click', (e) => {
    const el = /** @type {HTMLElement} */ (e.target).closest('[data-action]');
    if (!el) return;
    const action = /** @type {HTMLElement} */ (el).dataset.action;

    if (action === 'select') {
      saveNow();
      selectPlan(/** @type {HTMLElement} */ (el).dataset.name ?? null);
      return;
    }

    // The row carries the series, so a run acts on its own plan rather than on
    // whichever one happens to be open.
    const row = /** @type {HTMLElement} */ (el).closest('[data-series]');
    const series = row ? seriesById(/** @type {HTMLElement} */ (row).dataset.series) : undefined;
    runAction(action, /** @type {HTMLElement} */ (el).dataset.run, series);
  });

  activityFilterEl.addEventListener('change', () => {
    activityFilter = activityFilterEl.value;
    renderActivity();
    startTicker();
    saveViewState();
  });

  activityToggleEl.addEventListener('click', () => {
    activityCollapsed = !activityCollapsed;
    paintActivityCollapse();
    saveViewState();
  });

  detailEl.addEventListener('click', (e) => {
    const el = /** @type {HTMLElement} */ (e.target).closest('[data-action]');
    if (!el) return;
    const action = /** @type {HTMLElement} */ (el).dataset.action;
    const runId = /** @type {HTMLElement} */ (el).dataset.run;

    // Before the plan guard: the settings page has no plan behind it, and the
    // guard would swallow its one button.
    if (action === 'native-settings') return send({ type: 'openNativeSettings' });

    const plan = planByName(selected);
    if (!plan) return;
    const series = seriesForPlan(plan);

    if (action === 'open-editor') return send({ type: 'openInEditor', name: plan.name });
    // Before the `!series` guard: with nothing scheduled, this is what creates it.
    // Resuming a spent one-shot has to clear `spent`, or it will never fire.
    if (action === 'schedule-toggle') {
      if (!series) return send({ type: 'schedulePlan', name: plan.name });
      return patch(series.id, series.enabled ? { enabled: false } : { enabled: true, spent: false });
    }

    if (runAction(action, runId, series)) return;
    if (!series) return;

    if (action === 'unschedule') return send({ type: 'removeSeries', id: series.id });
    if (action === 'browse-cwd') return send({ type: 'browseCwd', id: series.id });

    if (action === 'picker-toggle') {
      pickerOpen = !pickerOpen;
      if (pickerOpen) pickerMonth = monthOf(series.nextRunAt);
      return render();
    }

    // Browsing months moves the view only. Nothing is scheduled until a day is
    // clicked, so paging back through last year must not patch anything.
    if (action === 'picker-prev' || action === 'picker-next') {
      const view = pickerMonth || monthOf(series.nextRunAt);
      const step = action === 'picker-next' ? 1 : -1;
      pickerMonth = new Date(view.getFullYear(), view.getMonth() + step, 1);
      return render();
    }

    // The day changes; the time of day is whatever the series already runs at.
    if (action === 'picker-day') {
      const [year, month, day] = /** @type {HTMLElement} */ (el).dataset.date.split('-').map(Number);
      const at = new Date(series.nextRunAt);
      const local = localStr(year, month - 1, day, at.getHours(), at.getMinutes());
      return patch(series.id, whenPatch(series, toUtcIso(local)));
    }

    if (action === 'day') {
      const day = Number(/** @type {HTMLElement} */ (el).dataset.day);
      const days = series.recurrence.daysOfWeek.includes(day)
        ? series.recurrence.daysOfWeek.filter((d) => d !== day)
        : [...series.recurrence.daysOfWeek, day];
      if (!days.length) return;
      return patch(series.id, { recurrence: { ...series.recurrence, daysOfWeek: days.sort() } });
    }
  });

  detailEl.addEventListener('input', (e) => {
    const el = /** @type {HTMLTextAreaElement} */ (e.target);
    if (el.dataset && el.dataset.field === 'editor') {
      editor.text = el.value;
      editor.dirty = true;
      paintEditorStatus();
      queueSave();
    }
  });

  detailEl.addEventListener('change', (e) => {
    const el = /** @type {HTMLInputElement|HTMLSelectElement} */ (e.target);

    // Before the guards below, which are about a plan and would swallow every
    // settings edit. On change only, never on input: a text field must not
    // rewrite settings.json on every keystroke.
    if (el.dataset && el.dataset.setting) {
      // An emptied number box is not a value — `Number('')` is 0, which would
      // silently write the field's minimum. NaN is refused by the host instead,
      // and the refusal is what snaps the control back to what is stored.
      const value =
        el.type === 'checkbox'
          ? /** @type {HTMLInputElement} */ (el).checked
          : el.type === 'number'
            ? (el.value === '' ? Number.NaN : Number(el.value))
            : el.value;
      return send({ type: 'updateSetting', key: el.dataset.setting, value });
    }

    const field = el.dataset ? el.dataset.field : undefined;
    if (!field || field === 'editor') return;

    const series = seriesForPlan(planByName(selected));
    if (!series) return;

    // The three time dropdowns are one value between them, so any of them
    // changing reads all three. The date is whatever the series already runs on.
    if (field === 'pickerHour' || field === 'pickerMinute' || field === 'pickerAmpm') {
      const read = (name) =>
        /** @type {HTMLSelectElement} */ (detailEl.querySelector(`[data-field="${name}"]`)).value;
      const at = new Date(series.nextRunAt);
      const hour = from12(Number(read('pickerHour')), read('pickerAmpm'));
      const local = localStr(at.getFullYear(), at.getMonth(), at.getDate(), hour, Number(read('pickerMinute')));
      return patch(series.id, whenPatch(series, toUtcIso(local)));
    }

    if (field === 'repeat') {
      const timeLocal = localTimeOf(series.nextRunAt);
      if (el.value === 'once') return patch(series.id, { recurrence: null });
      if (el.value === 'daily') {
        return patch(series.id, { recurrence: { daysOfWeek: [0, 1, 2, 3, 4, 5, 6], timeLocal } });
      }
      // Monthly takes its day from the When field, the way weekly takes its
      // weekday — so there is no second picker to keep in step with it.
      if (el.value === 'monthly') {
        return patch(series.id, {
          recurrence: { daysOfWeek: [], timeLocal, dayOfMonth: new Date(series.nextRunAt).getDate() }
        });
      }
      return patch(series.id, {
        recurrence: { daysOfWeek: [new Date(series.nextRunAt).getDay()], timeLocal }
      });
    }

    if (field === 'permissionMode') return patch(series.id, { permissionMode: el.value });

    // A model id belongs to one engine, so switching engines drops one the new
    // engine has never heard of rather than passing it on to fail at fire time.
    if (field === 'agent') {
      const next = state.agents.find((a) => a.id === el.value);
      const keeps = !!next && next.models.some((m) => m.value === (series.model || ''));
      customModel = false;
      return patch(series.id, { agent: el.value, model: keeps ? series.model : undefined });
    }

    if (field === 'model') {
      // Custom… is a UI state, not a value: it reveals the box below, and the
      // box is what patches.
      if (el.value === CUSTOM_MODEL) {
        customModel = true;
        return render();
      }
      customModel = false;
      return patch(series.id, { model: el.value || undefined });
    }

    if (field === 'customModel') return patch(series.id, { model: el.value.trim() || undefined });
  });

  // Blur-save, so switching away never loses an edit.
  detailEl.addEventListener(
    'focusout',
    (e) => {
      const el = /** @type {HTMLElement} */ (e.target);
      if (el.dataset && el.dataset.field === 'editor') saveNow();
    },
    true
  );

  window.addEventListener('beforeunload', saveNow);

  /**
   * Dismissing the When popover. Registered once here rather than inside
   * render(), which rebuilds the popover on every patch and would stack a
   * listener each time. The trigger's own click is handled by the delegate above
   * before this runs, and its target is inside `.when-picker`, so clicking the
   * trigger to close does not immediately reopen it.
   */
  document.addEventListener('click', (e) => {
    if (!pickerOpen) return;
    if (/** @type {HTMLElement} */ (e.target).closest('.when-picker')) return;
    pickerOpen = false;
    render();
  });

  document.addEventListener('keydown', (e) => {
    if (e.key !== 'Escape' || !pickerOpen) return;
    pickerOpen = false;
    render();
  });

  /**
   * A VS Code-style sash. Pointer capture is what makes the drag survive the
   * pointer leaving the 6px strip — without it, moving faster than the layout
   * repaints drops the drag.
   *
   * Measured from the shell's left edge and the Runs panel's own bottom edge, so
   * the banner and notice rows above cannot skew the maths.
   */
  function startSash(e, axis) {
    const sash = /** @type {HTMLElement} */ (e.currentTarget);
    e.preventDefault();
    sash.setPointerCapture(e.pointerId);
    sash.classList.add('is-active');
    document.body.classList.add('is-resizing');
    document.body.style.cursor = axis === 'x' ? 'col-resize' : 'row-resize';

    const move = (ev) => {
      if (axis === 'x') {
        libraryWidth = clampLibrary(ev.clientX - shellEl.getBoundingClientRect().left);
      } else {
        activityHeight = clampActivity(activityEl.getBoundingClientRect().bottom - ev.clientY);
      }
      applySizes();
    };

    const end = () => {
      sash.removeEventListener('pointermove', move);
      sash.removeEventListener('pointerup', end);
      sash.removeEventListener('lostpointercapture', end);
      sash.classList.remove('is-active');
      document.body.classList.remove('is-resizing');
      document.body.style.cursor = '';
      saveViewState();
    };

    sash.addEventListener('pointermove', move);
    sash.addEventListener('pointerup', end);
    sash.addEventListener('lostpointercapture', end);
  }

  librarySashEl.addEventListener('pointerdown', (e) => startSash(e, 'x'));
  activitySashEl.addEventListener('pointerdown', (e) => startSash(e, 'y'));

  /* A shrunken window must not leave a 560px library in a 600px tab. No
     render() here: the detail pane holds an unsaved editor buffer, and
     re-rendering on every resize tick would fight the debounced save. */
  window.addEventListener('resize', () => {
    if (libraryWidth !== null) libraryWidth = clampLibrary(libraryWidth);
    if (activityHeight !== null) activityHeight = clampActivity(activityHeight);
    applySizes();
  });

  document.getElementById('new-plan').addEventListener('click', () => send({ type: 'createPlan' }));

  document.getElementById('import-plan').addEventListener('click', () => send({ type: 'importPlan' }));
  document.getElementById('reveal-library').addEventListener('click', () => send({ type: 'revealLibrary' }));
  document.getElementById('reveal-results').addEventListener('click', () => send({ type: 'revealResults' }));
  document.getElementById('reveal-archive').addEventListener('click', () => send({ type: 'revealArchive' }));

  // A toggle, so the gear both opens the page and comes back from it. The save
  // is because the detail pane is about to stop being the plan editor.
  document.getElementById('open-settings').addEventListener('click', () => {
    saveNow();
    showSettings = !showSettings;
    render();
  });

  // The host may refuse — a run in flight belongs to the folder being left — and
  // answers either way with a fresh state, which puts the dropdown back if so.
  rootFolderEl.addEventListener('change', () =>
    send({ type: 'switchFolder', folder: rootFolderEl.value })
  );

  /** Moving a recurring series' time must move its rule too. */
  function whenPatch(series, iso) {
    const p = { nextRunAt: iso, spent: false };
    if (series.recurrence) {
      p.recurrence = { ...series.recurrence, timeLocal: localTimeOf(iso) };
      // Monthly has no day picker of its own: the When field is how you move it.
      if (series.recurrence.dayOfMonth) p.recurrence.dayOfMonth = new Date(iso).getDate();
    }
    return p;
  }

  /** The next future instant at a given ISO's local time of day, as UTC ISO. */
  function nextAtTimeOf(iso) {
    const src = new Date(iso);
    const at = new Date();
    at.setHours(src.getHours(), src.getMinutes(), 0, 0);
    if (at.getTime() <= Date.now()) at.setDate(at.getDate() + 1);
    return at.toISOString();
  }

  const patch = (id, p) => send({ type: 'updateSeries', id, patch: p });

  /** Moving to another plan drops the Model field's free-text box and the When
   *  popover, both of which belonged to the plan you were looking at. Picking a
   *  plan also leaves the settings page — it is what the detail pane is for. */
  function selectPlan(name) {
    if (name !== selected) {
      customModel = false;
      pickerOpen = false;
      pickerMonth = null;
    }
    showSettings = false;
    selected = name;
    render();
  }

  function showNotice(text) {
    noticeEl.textContent = text;
    noticeEl.hidden = false;
    clearTimeout(noticeTimer);
    noticeTimer = setTimeout(() => {
      noticeEl.hidden = true;
    }, 6000);
  }

  // ---------- drag and drop ----------

  function readDrop(dt) {
    const uriList = dt.getData('application/vnd.code.uri-list') || dt.getData('text/uri-list');
    if (uriList) {
      return uriList
        .split(/\r?\n/)
        .map((s) => s.trim())
        .filter((s) => s && !s.startsWith('#'));
    }
    // No path branch for an OS drop: Electron 32 removed File.path, and a
    // sandboxed webview has no other way to learn where a file lives. The drop
    // handler reads the contents instead.
    return [];
  }

  /** Only files/URIs count — a text drag inside the editor must be left alone. */
  function isFileDrag(dt) {
    return !!dt && Array.from(dt.types || []).some(
      (t) => t === 'Files' || t === 'application/vnd.code.uri-list' || t === 'text/uri-list'
    );
  }

  let dragDepth = 0;

  document.addEventListener('dragenter', (e) => {
    if (!isFileDrag(e.dataTransfer)) return;
    e.preventDefault();
    dragDepth++;
    document.body.classList.add('dragging');
  });

  document.addEventListener('dragover', (e) => {
    if (isFileDrag(e.dataTransfer)) e.preventDefault();
  });

  document.addEventListener('dragleave', (e) => {
    if (!isFileDrag(e.dataTransfer)) return;
    if (--dragDepth <= 0) {
      dragDepth = 0;
      document.body.classList.remove('dragging');
    }
  });

  document.addEventListener('drop', (e) => {
    if (!isFileDrag(e.dataTransfer)) return;
    e.preventDefault();
    dragDepth = 0;
    document.body.classList.remove('dragging');

    const items = readDrop(e.dataTransfer);
    if (items.length) {
      send({ type: 'drop', items });
      return;
    }

    // An OS drop can no longer say where the file lives, but the contents are
    // still readable — so copy it into the library, the same as Import does.
    // preventDefault() has already run above, and a File stays readable after
    // this handler returns, so reading asynchronously is safe.
    const files = Array.from(e.dataTransfer.files || []).filter(
      (f) => f.name.toLowerCase().endsWith('.md') && f.size < 1_000_000
    );
    if (!files.length) {
      showNotice('Could not read the dropped files — use Import instead.');
      return;
    }

    Promise.all(files.map(async (f) => ({ name: f.name, text: await f.text() })))
      .then((copies) => send({ type: 'dropText', files: copies }))
      .catch(() => showNotice('Could not read the dropped files — use Import instead.'));
  });

  // ---------- inbound ----------

  window.addEventListener('message', (event) => {
    const message = event.data;

    if (message.type === 'state') {
      state = message;
      if (selected && !planByName(selected)) selected = null;
      if (!selected && state.plans.length) selected = state.plans[0].name;
      render();
      return;
    }

    if (message.type === 'planText') {
      // A load only wins if you have not typed since asking for it.
      if (message.name === editor.name && !editor.dirty) {
        editor.text = message.text;
        editor.conflict = false;
        const area = /** @type {HTMLTextAreaElement|null} */ (detailEl.querySelector('[data-field="editor"]'));
        if (area) area.value = message.text;
        paintEditorStatus();
      }
      return;
    }

    if (message.type === 'planChanged') {
      // Never silently discard either side. Clean buffer reloads; dirty warns.
      if (message.name !== editor.name) return;
      if (editor.dirty) {
        editor.conflict = true;
        paintEditorStatus();
      } else {
        send({ type: 'loadPlan', name: message.name });
      }
      return;
    }

    if (message.type === 'select') {
      selectPlan(message.name);
      return;
    }

    if (message.type === 'notice') showNotice(message.text);
  });

  send({ type: 'ready' });
})();
